import XCTest
@testable import API2FileCore

final class AgentGuideGeneratorTests: XCTestCase {

    // MARK: - Helpers

    private func makeConfig(
        service: String = "test",
        displayName: String = "Test Service",
        resources: [ResourceConfig] = []
    ) -> AdapterConfig {
        AdapterConfig(
            service: service,
            displayName: displayName,
            version: "1.0",
            auth: AuthConfig(type: .bearer, keychainKey: "api2file.\(service).key"),
            resources: resources
        )
    }

    private func makeResource(
        name: String = "items",
        description: String? = nil,
        strategy: MappingStrategy = .onePerRecord,
        directory: String = "items",
        format: FileFormat = .json,
        idField: String? = nil,
        readOnly: Bool? = nil,
        interval: Int? = nil
    ) -> ResourceConfig {
        ResourceConfig(
            name: name,
            description: description,
            fileMapping: FileMappingConfig(
                strategy: strategy,
                directory: directory,
                format: format,
                idField: idField,
                readOnly: readOnly
            ),
            sync: interval != nil ? SyncConfig(interval: interval) : nil
        )
    }

    // MARK: - Root Guide Tests

    func testRootGuideContainsAllServices() {
        let services: [(serviceId: String, config: AdapterConfig)] = [
            ("monday", makeConfig(
                service: "monday",
                displayName: "Monday.com",
                resources: [makeResource(format: .csv)]
            )),
            ("notion", makeConfig(
                service: "notion",
                displayName: "Notion",
                resources: [makeResource(format: .markdown)]
            )),
            ("github", makeConfig(
                service: "github",
                displayName: "GitHub",
                resources: [makeResource(format: .json)]
            ))
        ]

        let guide = AgentGuideGenerator.generateRootGuide(
            services: services,
            serverPort: 24842
        )

        // Header
        XCTAssertTrue(guide.contains("# API2File — Cloud Data as Local Files"))
        XCTAssertTrue(guide.contains("<!-- Generated by API2File at"))

        // All services listed
        XCTAssertTrue(guide.contains("`monday/` — Monday.com (csv files)"))
        XCTAssertTrue(guide.contains("`notion/` — Notion (md files)"))
        XCTAssertTrue(guide.contains("`github/` — GitHub (json files)"))

        // How it works
        XCTAssertTrue(guide.contains("## How it works"))
        XCTAssertTrue(guide.contains("Files sync bidirectionally"))
        XCTAssertTrue(guide.contains("structured canonical records"))
        XCTAssertTrue(guide.contains(".api2file/file-links.json"))
        XCTAssertTrue(guide.contains(".api2file/cache/service.sqlite"))

        // Control API with correct port
        XCTAssertTrue(guide.contains("## Control API (localhost:24842)"))
        XCTAssertTrue(guide.contains("GET /api/services"))
        XCTAssertTrue(guide.contains("POST /api/services/:id/sync"))
        XCTAssertTrue(guide.contains("GET /api/services/:id/sql/tables"))
        XCTAssertTrue(guide.contains("POST /api/services/:id/sql/query"))
        XCTAssertTrue(guide.contains("GET /api/services/:id/sql/record?resource=...&recordId=..."))
        XCTAssertTrue(guide.contains("GET /api/services/:id/sql/open?resource=...&recordId=...&surface=canonical|projection"))
        XCTAssertTrue(guide.contains("query_and_open_first"))
    }

    // MARK: - Service Guide Tests

    func testServiceGuideIncludesResourceInfo() {
        let config = makeConfig(
            service: "monday",
            displayName: "Monday.com",
            resources: [
                makeResource(
                    name: "boards",
                    description: "Your Monday.com boards as CSV spreadsheets",
                    strategy: .collection,
                    directory: "boards",
                    format: .csv,
                    idField: "id",
                    interval: 30
                ),
                makeResource(
                    name: "updates",
                    description: "Activity updates from Monday.com",
                    strategy: .onePerRecord,
                    directory: "updates",
                    format: .json,
                    interval: 120
                )
            ]
        )

        let guide = AgentGuideGenerator.generateServiceGuide(
            config: config,
            serverPort: 24842
        )

        // Header
        XCTAssertTrue(guide.contains("# Monday.com — Synced via API2File"))
        XCTAssertTrue(guide.contains("syncs bidirectionally with your Monday.com account"))

        // Resource sections
        XCTAssertTrue(guide.contains("### boards/ (csv files)"))
        XCTAssertTrue(guide.contains("Your Monday.com boards as CSV spreadsheets"))
        XCTAssertTrue(guide.contains("**Strategy:** collection"))

        XCTAssertTrue(guide.contains("### updates/ (json files)"))
        XCTAssertTrue(guide.contains("Activity updates from Monday.com"))
        XCTAssertTrue(guide.contains("**Strategy:** one-per-record"))

        // App suggestions
        XCTAssertTrue(guide.contains("Numbers, Excel, or any text editor"))
        XCTAssertTrue(guide.contains("VS Code or any text editor"))

        // Control API
        XCTAssertTrue(guide.contains("curl localhost:24842/api/services/monday/sync"))
        XCTAssertTrue(guide.contains("curl localhost:24842/api/services/monday/status"))
        XCTAssertTrue(guide.contains("curl localhost:24842/api/services/monday/sql/record?resource=table_name\\&recordId=123"))
        XCTAssertTrue(guide.contains("curl localhost:24842/api/services/monday/sql/open?resource=table_name\\&recordId=123\\&surface=canonical"))
        XCTAssertTrue(guide.contains("Use MCP `query_and_open_first`"))

        // Canonical/projection guidance
        XCTAssertTrue(guide.contains("Hidden `.*.objects.json` files hold the structured canonical records"))
        XCTAssertTrue(guide.contains("`.api2file/file-links.json` links each projection to its canonical object file."))
        XCTAssertTrue(guide.contains("`.api2file/cache/service.sqlite` is a derived, read-only SQLite mirror"))
        XCTAssertTrue(guide.contains("Human-facing files are decoded back into canonical records before push"))
        XCTAssertTrue(guide.contains("The SQLite mirror updates after pull/push cycles and is read-only in v1"))
        XCTAssertTrue(guide.contains("Treat `.api2file/cache/service.sqlite` as read-only"))
    }

    func testWixServiceGuideMentionsRicosMarkdownFlow() {
        let config = makeConfig(
            service: "wix",
            displayName: "Wix",
            resources: [
                makeResource(
                    name: "blog-posts",
                    strategy: .onePerRecord,
                    directory: "blog",
                    format: .markdown
                )
            ]
        )

        let guide = AgentGuideGenerator.generateServiceGuide(
            config: config,
            serverPort: 24842
        )

        XCTAssertTrue(guide.contains("Wix blog Markdown files are converted to and from Wix Ricos rich content during sync"))
        XCTAssertFalse(guide.contains("Some current builds may still auto-push primarily from the human-facing files"))
    }

    func testCSVResourceIncludesIdColumnWarning() {
        let config = makeConfig(
            service: "monday",
            displayName: "Monday.com",
            resources: [
                makeResource(
                    name: "boards",
                    strategy: .collection,
                    directory: "boards",
                    format: .csv,
                    idField: "id"
                )
            ]
        )

        let guide = AgentGuideGenerator.generateServiceGuide(
            config: config,
            serverPort: 24842
        )

        // ID column warning in resource section
        XCTAssertTrue(guide.contains("**ID column:** `_id` — do not modify"))
        // Format constraint about CSV id column
        XCTAssertTrue(guide.contains("Don't modify the _id column in CSV files"))
    }

    func testReadOnlyResourceShowsReadOnlyNotice() {
        let config = makeConfig(
            service: "analytics",
            displayName: "Analytics",
            resources: [
                makeResource(
                    name: "reports",
                    description: "Read-only analytics reports",
                    strategy: .onePerRecord,
                    directory: "reports",
                    format: .json,
                    readOnly: true
                )
            ]
        )

        let guide = AgentGuideGenerator.generateServiceGuide(
            config: config,
            serverPort: 24842
        )

        XCTAssertTrue(guide.contains("**Read-only** — changes are not pushed back"))
    }

    // MARK: - Write Guides Tests

    func testWriteGuidesCreateFiles() throws {
        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("api2file-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tmpDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let services: [(serviceId: String, config: AdapterConfig)] = [
            ("monday", makeConfig(
                service: "monday",
                displayName: "Monday.com",
                resources: [makeResource(format: .csv)]
            ))
        ]

        try AgentGuideGenerator.writeGuides(
            rootDir: tmpDir,
            services: services,
            serverPort: 24842
        )

        // Root CLAUDE.md exists
        let rootPath = tmpDir.appendingPathComponent("CLAUDE.md").path
        XCTAssertTrue(FileManager.default.fileExists(atPath: rootPath))

        // SKILL.md written alongside CLAUDE.md
        let skillPath = tmpDir.appendingPathComponent("SKILL.md").path
        XCTAssertTrue(FileManager.default.fileExists(atPath: skillPath), "SKILL.md should be written next to CLAUDE.md")
        if FileManager.default.fileExists(atPath: skillPath) {
            let skillContent = try String(contentsOfFile: skillPath, encoding: .utf8)
            XCTAssertTrue(skillContent.contains("objects.json"), "SKILL.md should document .objects.json files")
            XCTAssertTrue(skillContent.contains("api2file"), "SKILL.md should have api2file frontmatter name")
        }

        // Service CLAUDE.md exists
        let servicePath = tmpDir.appendingPathComponent("monday/CLAUDE.md").path
        XCTAssertTrue(FileManager.default.fileExists(atPath: servicePath))

        // Verify content
        let rootContent = try String(contentsOfFile: rootPath, encoding: .utf8)
        XCTAssertTrue(rootContent.contains("Monday.com"))

        let serviceContent = try String(contentsOfFile: servicePath, encoding: .utf8)
        XCTAssertTrue(serviceContent.contains("Monday.com — Synced via API2File"))
    }

    func testServiceGuideDefaultDescription() {
        let config = makeConfig(
            service: "test",
            displayName: "Test Service",
            resources: [
                makeResource(
                    name: "items",
                    description: nil,
                    directory: "items",
                    format: .json
                )
            ]
        )

        let guide = AgentGuideGenerator.generateServiceGuide(
            config: config,
            serverPort: 24842
        )

        XCTAssertTrue(guide.contains("Synced items from Test Service"))
    }

    func testServiceGuideMirrorStrategy() {
        let config = makeConfig(
            service: "drive",
            displayName: "Google Drive",
            resources: [
                makeResource(
                    name: "files",
                    strategy: .mirror,
                    directory: "files",
                    format: .raw
                )
            ]
        )

        let guide = AgentGuideGenerator.generateServiceGuide(
            config: config,
            serverPort: 24842
        )

        XCTAssertTrue(guide.contains("**Strategy:** mirror"))
        XCTAssertTrue(guide.contains("Create a new file in `files/`. It will be uploaded to the remote."))
    }

    func testConstraintsSectionPresent() {
        let config = makeConfig(
            service: "test",
            displayName: "Test",
            resources: [makeResource(format: .json)]
        )

        let guide = AgentGuideGenerator.generateServiceGuide(
            config: config,
            serverPort: 24842
        )

        XCTAssertTrue(guide.contains("## Constraints"))
        XCTAssertTrue(guide.contains("Don't modify files in `.api2file/`"))
        XCTAssertTrue(guide.contains("Prefer the hidden `.*.objects.json` files for high-fidelity agent edits"))
    }
}
