import Foundation

/// Generates CLAUDE.md guide files that help AI agents understand
/// the API2File directory structure and how to interact with synced files.
public enum AgentGuideGenerator {

    // MARK: - Public API

    /// Generate the root ~/API2File/CLAUDE.md listing all services
    public static func generateRootGuide(
        services: [(serviceId: String, config: AdapterConfig)],
        serverPort: Int
    ) -> String {
        let timestamp = ISO8601DateFormatter().string(from: Date())
        var lines: [String] = []

        lines.append("<!-- Generated by API2File at \(timestamp) -->")
        lines.append("# API2File — Cloud Data as Local Files")
        lines.append("")
        lines.append("This directory syncs cloud service data to local files.")
        lines.append("Edit files here → changes push to the cloud automatically.")
        if services.contains(where: { $0.config.storageMode == .managedWorkspace }) {
            lines.append("Managed workspace services keep the last accepted version visible and may reject invalid edits.")
        }
        lines.append("")
        lines.append("## Connected Services")

        for (serviceId, config) in services {
            let primaryFormat = config.resources.first?.fileMapping.format ?? .json
            let displayName = ServiceIdentity.runtimeDisplayName(for: config, serviceID: serviceId)
            lines.append("- `\(serviceId)/` — \(displayName) (\(primaryFormat.rawValue) files)")
        }

        lines.append("")
        lines.append("## How it works")
        lines.append("- Files sync bidirectionally with cloud APIs")
        lines.append("- Hidden `.*.objects.json` files store the structured canonical records for each resource")
        lines.append("- `.api2file/file-links.json` maps human-facing files to their canonical object files")
        lines.append("- `.api2file/cache/service.sqlite` exposes a read-only query mirror for analysis and agents")
        lines.append("- Human-facing files (CSV, MD, ICS, etc.) are projections optimized for native apps and browsing")
        lines.append("- Changes are git-committed automatically")
        lines.append("- Server is source of truth for conflicts")
        lines.append("- See each service's CLAUDE.md for details")
        lines.append("")
        lines.append("## Control API (localhost:\(serverPort))")
        lines.append("- GET /api/services — list all services + status + siteUrls")
        lines.append("- POST /api/services/:id/sync — force sync")
        lines.append("- GET /api/services/:id/conflicts — list conflicts")
        lines.append("- GET /api/services/:id/sql/tables — list queryable SQLite tables")
        lines.append("- POST /api/services/:id/sql/query — run read-only SQL against the local mirror")
        lines.append("- GET /api/services/:id/sql/record?resource=...&recordId=... — resolve a record to file paths")
        lines.append("- GET /api/services/:id/sql/open?resource=...&recordId=...&surface=canonical|projection — open a record file")
        lines.append("")
        lines.append("## MCP Browser Tools")
        lines.append("")
        lines.append("You have MCP tools to control a browser and verify your changes visually:")
        lines.append("1. `get_services` → discover services and their site URLs")
        lines.append("2. Edit files locally (CSV, JSON, MD, etc.)")
        lines.append("3. `sync({serviceId})` → push changes to the cloud")
        lines.append("4. `navigate({siteUrl})` → open the site in the browser")
        lines.append("5. `screenshot()` → capture the page (saves to file, use Read to view)")
        lines.append("6. `get_dom({selector})` → inspect specific elements")
        lines.append("")
        lines.append("For data lookup workflows, prefer `list_sql_tables`, `query_sql`, `get_record_by_id`, `open_record_file`, or `query_and_open_first` before editing.")
        lines.append("")

        return lines.joined(separator: "\n")
    }

    /// Generate a per-service CLAUDE.md from its adapter config
    public static func generateServiceGuide(
        serviceId: String,
        config: AdapterConfig,
        serverPort: Int
    ) -> String {
        let timestamp = ISO8601DateFormatter().string(from: Date())
        let displayName = ServiceIdentity.runtimeDisplayName(for: config, serviceID: serviceId)
        var lines: [String] = []

        lines.append("<!-- Generated by API2File at \(timestamp) -->")
        lines.append("# \(displayName) — Synced via API2File")
        lines.append("")
        lines.append("This folder syncs bidirectionally with your \(displayName) account.")
        lines.append("Edit files locally → changes push to \(displayName) automatically.")
        if config.storageMode == .managedWorkspace {
            lines.append("This service uses API2File managed workspace mode: rejected edits are restored to the last accepted version.")
        }
        lines.append("Hidden `.*.objects.json` files hold the structured canonical records; user-facing files are projections for apps and easy browsing.")
        lines.append("`.api2file/file-links.json` links each projection to its canonical object file.")
        lines.append("`.api2file/cache/service.sqlite` is a derived, read-only SQLite mirror for search, SQL, and agent analysis.")
        lines.append("")
        lines.append("## Resources")

        for resource in config.resources {
            let mapping = resource.fileMapping
            let format = mapping.format
            let dir = mapping.directory
            let appSuggestion = Self.appSuggestion(for: format)
            let strategyLabel = Self.strategyLabel(for: mapping.strategy)
            let description = resource.description ?? "Synced \(resource.name) from \(displayName)"

            lines.append("")
            lines.append("### \(dir)/ (\(format.rawValue) files)")
            lines.append(description)
            lines.append("")
            lines.append("**File format:** \(format.rawValue) (opens in \(appSuggestion))")
            lines.append("**Strategy:** \(strategyLabel)")

            if mapping.readOnly == true {
                lines.append("**Read-only** — changes are not pushed back")
            }

            if let idField = mapping.idField {
                lines.append("**ID column:** `_\(idField)` — do not modify")
            }

            lines.append("")

            let interval = resource.sync?.interval ?? 60
            lines.append("**To update:** Edit the file and save. Changes sync within \(interval)s.")
            if config.storageMode == .managedWorkspace {
                lines.append("**Managed commit:** \(resource.effectiveManagedCommitPolicy.rawValue)")
            }
            lines.append("**To create:** \(Self.createInstructions(for: mapping.strategy, format: format, directory: dir))")
            lines.append("**To delete:** Delete the file. The record is removed after 5s grace period.")

            // Resource-level URLs for visual verification
            if let siteUrl = resource.siteUrl, !siteUrl.isEmpty {
                lines.append("**View on site:** `navigate(\"\(siteUrl)\")`")
            }
            if let dashboardUrl = resource.dashboardUrl, !dashboardUrl.isEmpty {
                lines.append("**Manage in dashboard:** `navigate(\"\(dashboardUrl)\")`")
            }
        }

        // Sync behavior section
        let defaultInterval = config.resources.first?.sync?.interval ?? 60
        lines.append("")
        lines.append("## Sync behavior")
        lines.append("- Poll interval: \(defaultInterval) seconds")
        lines.append("- Local changes push within 500ms of saving")
        lines.append("- Canonical object files are the intended local source of truth for structured edits")
        lines.append("- Human-facing files are decoded back into canonical records before push")
        lines.append("- The SQLite mirror updates after pull/push cycles and is read-only in v1")
        if config.service == "wix" {
            lines.append("- Wix blog Markdown files are converted to and from Wix Ricos rich content during sync")
        }
        lines.append("- Server is source of truth — conflicts create `.conflict` files")
        lines.append("- All changes are git-committed automatically")

        // Control API section
        lines.append("")
        lines.append("## Control API")
        lines.append("```")
        lines.append("curl localhost:\(serverPort)/api/services/\(serviceId)/sync    # Force immediate sync")
        lines.append("curl localhost:\(serverPort)/api/services/\(serviceId)/status   # Check sync status")
        lines.append("curl localhost:\(serverPort)/api/services/\(serviceId)/sql/tables")
        lines.append("curl -X POST localhost:\(serverPort)/api/services/\(serviceId)/sql/query -H 'Content-Type: application/json' -d '{\"query\":\"SELECT * FROM table_name LIMIT 5\"}'")
        lines.append("curl localhost:\(serverPort)/api/services/\(serviceId)/sql/record?resource=table_name\\&recordId=123")
        lines.append("curl localhost:\(serverPort)/api/services/\(serviceId)/sql/open?resource=table_name\\&recordId=123\\&surface=canonical")
        lines.append("```")
        lines.append("Use MCP `query_and_open_first` when you want to jump from a SQL match straight to the synced file in one step.")

        // MCP Browser section
        lines.append("")
        lines.append("## Visual Verification (MCP Browser)")
        lines.append("")
        lines.append("After editing files, verify your changes visually:")
        lines.append("1. `sync(\"\(serviceId)\")` → push changes")
        if let siteUrl = config.siteUrl {
            lines.append("2. `navigate(\"\(siteUrl)\")` → view the public site")
        } else {
            lines.append("2. `navigate({url})` → open the service's site")
        }
        if let dashboardUrl = config.dashboardUrl {
            lines.append("   Or `navigate(\"\(dashboardUrl)\")` → open the management dashboard")
        }
        lines.append("3. `screenshot()` → capture the page (saves to file, use Read to view)")
        lines.append("4. `get_dom({selector})` → inspect specific elements")

        // Constraints section
        lines.append("")
        lines.append("## Constraints")
        lines.append("- Don't modify files in `.api2file/` — these are internal")
        lines.append("- Treat `.api2file/cache/service.sqlite` as read-only; edit canonical object files or human-facing projections instead")
        lines.append("- Prefer the hidden `.*.objects.json` files for high-fidelity agent edits; avoid editing both an object file and its human-facing projection before the same sync cycle")
        for constraint in Self.formatConstraints(for: config) {
            lines.append("- \(constraint)")
        }
        lines.append("")

        return lines.joined(separator: "\n")
    }

    /// Write the generated guides to disk
    public static func writeGuides(
        rootDir: URL,
        services: [(serviceId: String, config: AdapterConfig)],
        serverPort: Int
    ) throws {
        let fm = FileManager.default

        // Write root CLAUDE.md
        let rootGuide = generateRootGuide(services: services, serverPort: serverPort)
        let rootPath = rootDir.appendingPathComponent("CLAUDE.md")
        try rootGuide.write(to: rootPath, atomically: true, encoding: .utf8)

        // Write SKILL.md alongside CLAUDE.md
        if let skill = loadSkillContent() {
            let skillPath = rootDir.appendingPathComponent("SKILL.md")
            try skill.write(to: skillPath, atomically: true, encoding: .utf8)
        }

        // Write per-service CLAUDE.md
        for (serviceId, config) in services {
            let serviceDir = rootDir.appendingPathComponent(serviceId)
            if !fm.fileExists(atPath: serviceDir.path) {
                try fm.createDirectory(at: serviceDir, withIntermediateDirectories: true)
            }
            let serviceGuide = generateServiceGuide(serviceId: serviceId, config: config, serverPort: serverPort)
            let servicePath = serviceDir.appendingPathComponent("CLAUDE.md")
            try serviceGuide.write(to: servicePath, atomically: true, encoding: .utf8)
        }
    }

    // MARK: - Skill Content

    /// Load SKILL.md from the bundle (falls back gracefully if not found)
    private static func loadSkillContent() -> String? {
        #if SWIFT_PACKAGE
        let bundle = Bundle.module
        #else
        let bundle = Bundle.main
        #endif
        if let url = bundle.url(forResource: "SKILL", withExtension: "md", subdirectory: "Resources"),
           let content = try? String(contentsOf: url) {
            return content
        }
        if let url = bundle.url(forResource: "SKILL", withExtension: "md"),
           let content = try? String(contentsOf: url) {
            return content
        }
        return nil
    }

    // MARK: - Private Helpers

    private static func appSuggestion(for format: FileFormat) -> String {
        switch format {
        case .csv:      return "Numbers, Excel, or any text editor"
        case .json:     return "VS Code or any text editor"
        case .html:     return "any browser or text editor"
        case .markdown: return "any text editor"
        case .yaml:     return "any text editor"
        case .text:     return "any text editor"
        case .raw:      return "any text editor"
        case .ics:      return "Calendar or any text editor"
        case .vcf:      return "Contacts or any text editor"
        case .eml:      return "Mail or any text editor"
        case .svg:      return "any browser or vector editor"
        case .webloc:   return "Safari or any browser"
        case .xlsx:     return "Numbers or Excel"
        case .docx:     return "Pages or Word"
        case .pptx:     return "Keynote or PowerPoint"
        }
    }

    private static func strategyLabel(for strategy: MappingStrategy) -> String {
        switch strategy {
        case .onePerRecord: return "one-per-record"
        case .collection:   return "collection"
        case .mirror:       return "mirror"
        }
    }

    private static func createInstructions(
        for strategy: MappingStrategy,
        format: FileFormat,
        directory: String
    ) -> String {
        switch strategy {
        case .onePerRecord:
            return "Create a new `.\(format.rawValue)` file in `\(directory)/`. It will be pushed as a new record."
        case .collection:
            return "Add a new row/entry to the existing file. It will be pushed as a new record."
        case .mirror:
            return "Create a new file in `\(directory)/`. It will be uploaded to the remote."
        }
    }

    private static func formatConstraints(for config: AdapterConfig) -> [String] {
        var constraints: [String] = []
        var seenFormats: Set<String> = []

        for resource in config.resources {
            let format = resource.fileMapping.format
            let key = format.rawValue
            guard !seenFormats.contains(key) else { continue }
            seenFormats.insert(key)

            switch format {
            case .csv:
                if let idField = resource.fileMapping.idField {
                    constraints.append("Don't modify the _\(idField) column in CSV files — it links rows to remote records")
                }
            case .json:
                if let idField = resource.fileMapping.idField {
                    constraints.append("Don't modify the `_\(idField)` field in JSON files — it links records to remote entries")
                }
            case .xlsx:
                constraints.append("XLSX files must be saved/closed before sync can read changes")
            case .docx:
                constraints.append("DOCX files must be saved/closed before sync can read changes")
            default:
                break
            }
        }

        return constraints
    }
}
