import Foundation

/// Generates CLAUDE.md guide files that help AI agents understand
/// the API2File directory structure and how to interact with synced files.
public enum AgentGuideGenerator {

    // MARK: - Public API

    /// Generate the root ~/API2File/CLAUDE.md listing all services
    public static func generateRootGuide(
        services: [(serviceId: String, config: AdapterConfig)],
        serverPort: Int
    ) -> String {
        let timestamp = ISO8601DateFormatter().string(from: Date())
        var lines: [String] = []

        lines.append("<!-- Generated by API2File at \(timestamp) -->")
        lines.append("# API2File — Cloud Data as Local Files")
        lines.append("")
        lines.append("This directory syncs cloud service data to local files.")
        lines.append("Edit files here → changes push to the cloud automatically.")
        lines.append("")
        lines.append("## Connected Services")

        for (serviceId, config) in services {
            let primaryFormat = config.resources.first?.fileMapping.format ?? .json
            lines.append("- `\(serviceId)/` — \(config.displayName) (\(primaryFormat.rawValue) files)")
        }

        lines.append("")
        lines.append("## How it works")
        lines.append("- Files sync bidirectionally with cloud APIs")
        lines.append("- Changes are git-committed automatically")
        lines.append("- Server is source of truth for conflicts")
        lines.append("- See each service's CLAUDE.md for details")
        lines.append("")
        lines.append("## Control API (localhost:\(serverPort))")
        lines.append("- GET /api/services — list all services + status")
        lines.append("- POST /api/services/:id/sync — force sync")
        lines.append("- GET /api/services/:id/conflicts — list conflicts")
        lines.append("")

        return lines.joined(separator: "\n")
    }

    /// Generate a per-service CLAUDE.md from its adapter config
    public static func generateServiceGuide(
        config: AdapterConfig,
        serverPort: Int
    ) -> String {
        let timestamp = ISO8601DateFormatter().string(from: Date())
        var lines: [String] = []

        lines.append("<!-- Generated by API2File at \(timestamp) -->")
        lines.append("# \(config.displayName) — Synced via API2File")
        lines.append("")
        lines.append("This folder syncs bidirectionally with your \(config.displayName) account.")
        lines.append("Edit files locally → changes push to \(config.displayName) automatically.")
        lines.append("")
        lines.append("## Resources")

        for resource in config.resources {
            let mapping = resource.fileMapping
            let format = mapping.format
            let dir = mapping.directory
            let appSuggestion = Self.appSuggestion(for: format)
            let strategyLabel = Self.strategyLabel(for: mapping.strategy)
            let description = resource.description ?? "Synced \(resource.name) from \(config.displayName)"

            lines.append("")
            lines.append("### \(dir)/ (\(format.rawValue) files)")
            lines.append(description)
            lines.append("")
            lines.append("**File format:** \(format.rawValue) (opens in \(appSuggestion))")
            lines.append("**Strategy:** \(strategyLabel)")

            if mapping.readOnly == true {
                lines.append("**Read-only** — changes are not pushed back")
            }

            if let idField = mapping.idField {
                lines.append("**ID column:** `_\(idField)` — do not modify")
            }

            lines.append("")

            let interval = resource.sync?.interval ?? 60
            lines.append("**To update:** Edit the file and save. Changes sync within \(interval)s.")
            lines.append("**To create:** \(Self.createInstructions(for: mapping.strategy, format: format, directory: dir))")
            lines.append("**To delete:** Delete the file. The record is removed after 5s grace period.")
        }

        // Sync behavior section
        let defaultInterval = config.resources.first?.sync?.interval ?? 60
        lines.append("")
        lines.append("## Sync behavior")
        lines.append("- Poll interval: \(defaultInterval) seconds")
        lines.append("- Local changes push within 500ms of saving")
        lines.append("- Server is source of truth — conflicts create `.conflict` files")
        lines.append("- All changes are git-committed automatically")

        // Control API section
        lines.append("")
        lines.append("## Control API")
        lines.append("```")
        lines.append("curl localhost:\(serverPort)/api/services/\(config.service)/sync    # Force immediate sync")
        lines.append("curl localhost:\(serverPort)/api/services/\(config.service)/status   # Check sync status")
        lines.append("```")

        // Constraints section
        lines.append("")
        lines.append("## Constraints")
        lines.append("- Don't modify files in `.api2file/` — these are internal")
        for constraint in Self.formatConstraints(for: config) {
            lines.append("- \(constraint)")
        }
        lines.append("")

        return lines.joined(separator: "\n")
    }

    /// Write the generated guides to disk
    public static func writeGuides(
        rootDir: URL,
        services: [(serviceId: String, config: AdapterConfig)],
        serverPort: Int
    ) throws {
        let fm = FileManager.default

        // Write root CLAUDE.md
        let rootGuide = generateRootGuide(services: services, serverPort: serverPort)
        let rootPath = rootDir.appendingPathComponent("CLAUDE.md")
        try rootGuide.write(to: rootPath, atomically: true, encoding: .utf8)

        // Write per-service CLAUDE.md
        for (serviceId, config) in services {
            let serviceDir = rootDir.appendingPathComponent(serviceId)
            if !fm.fileExists(atPath: serviceDir.path) {
                try fm.createDirectory(at: serviceDir, withIntermediateDirectories: true)
            }
            let serviceGuide = generateServiceGuide(config: config, serverPort: serverPort)
            let servicePath = serviceDir.appendingPathComponent("CLAUDE.md")
            try serviceGuide.write(to: servicePath, atomically: true, encoding: .utf8)
        }
    }

    // MARK: - Private Helpers

    private static func appSuggestion(for format: FileFormat) -> String {
        switch format {
        case .csv:      return "Numbers, Excel, or any text editor"
        case .json:     return "VS Code or any text editor"
        case .html:     return "any browser or text editor"
        case .markdown: return "any text editor"
        case .yaml:     return "any text editor"
        case .text:     return "any text editor"
        case .raw:      return "any text editor"
        case .ics:      return "Calendar or any text editor"
        case .vcf:      return "Contacts or any text editor"
        case .eml:      return "Mail or any text editor"
        case .svg:      return "any browser or vector editor"
        case .webloc:   return "Safari or any browser"
        case .xlsx:     return "Numbers or Excel"
        case .docx:     return "Pages or Word"
        }
    }

    private static func strategyLabel(for strategy: MappingStrategy) -> String {
        switch strategy {
        case .onePerRecord: return "one-per-record"
        case .collection:   return "collection"
        case .mirror:       return "mirror"
        }
    }

    private static func createInstructions(
        for strategy: MappingStrategy,
        format: FileFormat,
        directory: String
    ) -> String {
        switch strategy {
        case .onePerRecord:
            return "Create a new `.\(format.rawValue)` file in `\(directory)/`. It will be pushed as a new record."
        case .collection:
            return "Add a new row/entry to the existing file. It will be pushed as a new record."
        case .mirror:
            return "Create a new file in `\(directory)/`. It will be uploaded to the remote."
        }
    }

    private static func formatConstraints(for config: AdapterConfig) -> [String] {
        var constraints: [String] = []
        var seenFormats: Set<String> = []

        for resource in config.resources {
            let format = resource.fileMapping.format
            let key = format.rawValue
            guard !seenFormats.contains(key) else { continue }
            seenFormats.insert(key)

            switch format {
            case .csv:
                if let idField = resource.fileMapping.idField {
                    constraints.append("Don't modify the _\(idField) column in CSV files — it links rows to remote records")
                }
            case .json:
                if let idField = resource.fileMapping.idField {
                    constraints.append("Don't modify the `_\(idField)` field in JSON files — it links records to remote entries")
                }
            case .xlsx:
                constraints.append("XLSX files must be saved/closed before sync can read changes")
            case .docx:
                constraints.append("DOCX files must be saved/closed before sync can read changes")
            default:
                break
            }
        }

        return constraints
    }
}
